// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgOrgcG8HsrHECMXPL0F_LA3X-U6EuCJk',
    appId: '1:87459027434:web:551113818a049a9b6bfa93',
    messagingSenderId: '87459027434',
    projectId: 'pawpalv1',
    authDomain: 'pawpalv1.firebaseapp.com',
    storageBucket: 'pawpalv1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa1prAQgnqMwjntP7HwKOw5xtzdjmP6Pk',
    appId: '1:87459027434:android:826b9517122358b26bfa93',
    messagingSenderId: '87459027434',
    projectId: 'pawpalv1',
    storageBucket: 'pawpalv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ssf6uAVvYPYIPUndPucJ5P7vjXAlA6k',
    appId: '1:87459027434:ios:1bcc524e4861cfe96bfa93',
    messagingSenderId: '87459027434',
    projectId: 'pawpalv1',
    storageBucket: 'pawpalv1.firebasestorage.app',
    iosBundleId: 'com.example.pawpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ssf6uAVvYPYIPUndPucJ5P7vjXAlA6k',
    appId: '1:87459027434:ios:1bcc524e4861cfe96bfa93',
    messagingSenderId: '87459027434',
    projectId: 'pawpalv1',
    storageBucket: 'pawpalv1.firebasestorage.app',
    iosBundleId: 'com.example.pawpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgOrgcG8HsrHECMXPL0F_LA3X-U6EuCJk',
    appId: '1:87459027434:web:314df53b1a54b8a26bfa93',
    messagingSenderId: '87459027434',
    projectId: 'pawpalv1',
    authDomain: 'pawpalv1.firebaseapp.com',
    storageBucket: 'pawpalv1.firebasestorage.app',
  );
}
